In [ ]:
import numpy as np

a_list = [1,2,3,4,5]
a_np = np.array(a_list)
type(a_list)

list

In [ ]:
type(a_np)

numpy.ndarray

In [ ]:
a_list = list(range(1,101))
sum(a_list)

5050

In [ ]:
a_np = np.arange(1,101, dtype=np.int64)
sum(a_np)

5050

In [ ]:
a_np = np.linspace(0,1,10)
a_np

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
from time import time

start = time()
#1~1000000까지 더하기 - 일반 리스트 사용
a_list = list(range(1, 1_000_001))
print('sum : ', sum(a_list))
end = time()

print('calc time : {}'.format(end-start))

start = time()
#1~1000000까지 더하기 - numpy 사용
a_np = np.arange(1, 1_000_001, dtype=np.int64)
print('sum : ', a_np.sum())
end = time()

print('calc time : {}'.format(end-start))

sum :  500000500000
calc time : 0.06641054153442383
sum :  500000500000
calc time : 0.006441593170166016


여러분들이 해야할 실습 과제는 다음과 같다.

1. r1부터 r10까지의 결과를 각각 출력해본다.
2. 해당 결과를 확인하고, 연산자 및 함수가 어떤 역할을 하는가 정리한다.

함수나 연산자의 사용법을 일일이 여러분에게 설명하는 것보다는 여러분 스스로 학습해 보는것이 더 도움이 되기 때문에 직접 확인하고 과제로 제출하기로 한다.

In [ ]:
import numpy as np
a_np = np.array([[1, 2, 3], [4, 5, 6]])
b_np = np.array([[1, 3, 5], [2, 4, 6]])

r1 = np.any(a_np > 3) 
r2 = np.all((a_np > 3)) 
r3 = a_np >= b_np
r4 = a_np[a_np >= b_np]
r5 = np.where(a_np > 2)
r6 = np.where(a_np > 2, a_np, 0)
r7 = np.where(a_np > 2, a_np*2, 1)
r8 = np.argmax(a_np)
r9 = np.argmax(a_np, axis=1)
r10 = np.argmax(a_np, axis=0)

In [ ]:
import numpy as np
a_np = np.array([[1, 2, 3], [4, 5, 6]])
b_np = np.array([[1, 3, 5], [2, 4, 6]])

r1 = np.any(a_np > 3) 
r2 = np.all((a_np > 3)) 
r3 = a_np >= b_np
r4 = a_np[a_np >= b_np]
r5 = np.where(a_np > 2)
r6 = np.where(a_np > 2, a_np, 0)
r7 = np.where(a_np > 2, a_np*2, 1)
r8 = np.argmax(a_np)
r9 = np.argmax(a_np, axis=1)
r10 = np.argmax(a_np, axis=0)

num = 1
r_list = [r1,r2,r3,r4,r5,r6,r7,r8,r9,r10]
r_real_list = [
    'r1 = np.any(a_np > 3)',
    'r2 = np.all((a_np > 3))', 
    'r3 = a_np >= b_np',
    'r4 = a_np[a_np >= b_np]',
    'r5 = np.where(a_np > 2)',
    'r6 = np.where(a_np > 2, a_np, 0)',
    'r7 = np.where(a_np > 2, a_np*2, 1)',
    'r8 = np.argmax(a_np)',
    'r9 = np.argmax(a_np, axis=1)',
    'r10 = np.argmax(a_np, axis=0)',
    ]
r_explain_list = [
    'np_any()항수는 괄호 안의 조건에 해당하는 요소가 있는지 판정하는 함수이다.', #r1's explain
    'np_all()함수는 괄호 안의 조건에 모든 요소가 해당하는지 판정하는 함수이다. ', #r2's explain
    '>=(비교) 연산자로 각각의 배열의 위치가 같은 요소끼리 대소비교가 가능하다.', #r3's explain
    'a_np[a_np >= b_np]로 a_np의 요소 중 []괄호 안의 조건에 맞는 요소만 리스트로 가지고 온다.', #r4's explain
    'np_where()로 괄호 안의 조건에 맞는 요소의 인덱스를 행 리스트, 열 리스트 순서로 출력한다.', #r5's explain
    'np.where(a_np > 2, a_np, 0)으로 괄호 안에 조건문에 참 요소는 a_np, 거짓 요소는 0으로 할당한다.', #r6's explain
    'np.where(a_np > 2, a_np*2, 1)으로 괄호 안에 조건문에 참 요소는 a_np*2, 거짓 요소는 1로 할당한다.', #r7's explain
    'np.argmax()함수는 괄호 안의 배열의 최대 값의 1차원 리스트로 볼 때의 인덱스를 반환한다.', #r8's explain
    'np.argmax(a_np, axis=1)함수는 a_np 배열의 최대 값의 인덱스를 행 기준으로 비교해 반환한다.', #r9's explain
    'np.argmax(a_np, axis=0)함수는 a_np 배열의 최대 값의 인덱스를 열 기준으로 비교해 반환한다.', #r10's explain
    ]
for i in range(0,len(r_list)):
  print('r{} = {}'.format(num,r_list[i]))
  print(r_real_list[i])
  print('r{}에서 {}'.format(num,r_explain_list[i]))
  print('-'*40)
  num+=1

while(True):
  exit=input('Enter를 누르면 종료\n')
  if(exit==''):break

r1 = True
r1 = np.any(a_np > 3)
r1에서 np_any()항수는 괄호 안의 조건에 해당하는 요소가 있는지 판정하는 함수이다.
----------------------------------------
r2 = False
r2 = np.all((a_np > 3))
r2에서 np_all()함수는 괄호 안의 조건에 모든 요소가 해당하는지 판정하는 함수이다. 
----------------------------------------
r3 = [[ True False False]
 [ True  True  True]]
r3 = a_np >= b_np
r3에서 >=(비교) 연산자로 각각의 배열의 위치가 같은 요소끼리 대소비교가 가능하다.
----------------------------------------
r4 = [1 4 5 6]
r4 = a_np[a_np >= b_np]
r4에서 a_np[a_np >= b_np]로 a_np의 요소 중 []괄호 안의 조건에 맞는 요소만 리스트로 가지고 온다.
----------------------------------------
r5 = (array([0, 1, 1, 1]), array([2, 0, 1, 2]))
r5 = np.where(a_np > 2)
r5에서 np_where()로 괄호 안의 조건에 맞는 요소의 인덱스를 행 리스트, 열 리스트 순서로 출력한다.
----------------------------------------
r6 = [[0 0 3]
 [4 5 6]]
r6 = np.where(a_np > 2, a_np, 0)
r6에서 np.where(a_np > 2, a_np, 0)으로 괄호 안에 조건문에 참 요소는 a_np, 거짓 요소는 0으로 할당한다.
----------------------------------------
r7 = [[ 1  1  6]
 [ 8 10 12]]
r7 = np.where(a_np > 2, a_np*2, 1)
r7에서 np.where(a_np > 2, a_np*2,